# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 23:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('name', models.CharField(db_column='Name', max_length=45)),
                ('age', models.IntegerField(db_column='Age')),
                ('animal_id', models.IntegerField(db_column='Animal_id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'animals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnimalShelters',
            fields=[
                ('name', models.CharField(db_column='Name', max_length=45)),
                ('shelter_id', models.IntegerField(db_column='Shelter_id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'animal_shelters',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('name', models.CharField(db_column='Name', max_length=50)),
                ('employee_id', models.IntegerField(db_column='Employee_id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grafts',
            fields=[
                ('graft_id', models.IntegerField(db_column='Graft_id', primary_key=True, serialize=False)),
                ('disease', models.CharField(db_column='Disease', max_length=45)),
                ('periodicity', models.IntegerField(db_column='Periodicity')),
                ('type', models.CharField(db_column='Type', max_length=45)),
            ],
            options={
                'db_table': 'grafts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('name', models.CharField(db_column='Name', max_length=50, primary_key=True, serialize=False)),
                ('salary', models.IntegerField(db_column='Salary')),
            ],
            options={
                'db_table': 'positions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('breed', models.CharField(db_column='Breed', max_length=45, primary_key=True, serialize=False)),
                ('type', models.CharField(db_column='Type', max_length=45)),
            ],
            options={
                'db_table': 'types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnimalsHasGrafts',
            fields=[
                ('animals_animal', models.ForeignKey(db_column='Animals_Animal_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='forms.Animals')),
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
            ],
            options={
                'db_table': 'animals_has_grafts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnimalSheltersHasPositions',
            fields=[
                ('animal_shelters_shelter', models.ForeignKey(db_column='Animal shelters_Shelter_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='forms.AnimalShelters')),
            ],
            options={
                'db_table': 'animal_shelters_has_positions',
                'managed': False,
            },
        ),
    ]
